### ISSUE TITLE
Receiving a connection error

### ISSUE THREAD

**Issue by BrosefAmelion** [sanyarnd/vocadb-notification-reader#12]
Tried some basic troubleshooting like disabling adblock, logging out of the main site but no dice.

**Comment by sanyarnd** [comment]
https://unofficial-vocadb-ntf-reader.herokuapp.com/login
does this page work?

Can you try something like `curl -v https://unofficial-vocadb-ntf-reader.herokuapp.com/login` and post output here?

If no curl is available on your platform, can you show the log in network requests in browser devtools (F12 -> Network, then reload page)

**Comment by BrosefAmelion** [comment]
The url gives the same connection error

```
Connected to unofficial-vocadb-ntf-reader.herokuapp.com (23.22.130.173) port 443 (#0)
* schannel: disabled automatic use of client certificate
* schannel: ALPN, offering http/1.1
* ALPN, server did not agree to a protocol
> GET /login HTTP/1.1
> Host: unofficial-vocadb-ntf-reader.herokuapp.com
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Connection: keep-alive
< Server: nginx/1.20.1
< Date: Mon, 14 Feb 2022 14:19:12 GMT
< Content-Type: text/html
< Content-Length: 1416
< Last-Modified: Mon, 31 May 2021 23:37:26 GMT
< Etag: "60b57336-588"
< Accept-Ranges: bytes
< Via: 1.1 vegur
<
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/favicon.ico"><title>Login</title><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@latest/css/materialdesignicons.min.css"><link href="/js/chunk-2d224eee.8982b609.js" rel="prefetch"><link href="/css/chunk-common.1339dc95.css" rel="preload" as="style"><link href="/css/chunk-vendors.be0f277c.css" rel="preload" as="style"><link href="/css/login.96719eee.css" rel="preload" as="style"><link href="/js/chunk-common.033021d0.js" rel="preload" as="script"><link href="/js/chunk-vendors.eff769b2.js" rel="preload" as="script"><link href="/js/login.7d97a46c.js" rel="preload" as="script"><link href="/css/chunk-vendors.be0f277c.css" rel="stylesheet"><link href="/css/chunk-common.1339dc95.css" rel="stylesheet"><link href="/css/login.96719eee.css" rel="stylesheet"></head><body><noscript><strong>We're sorry but Login doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div><script src="/js/chunk-vendors.eff769b2.js"></script><script src="/js/chunk-common.033021d0.js"></script><script src="/js/login.7d97a46c.js"></script></body></html>

* Connection #0 to host unofficial-vocadb-ntf-reader.herokuapp.com left intact
```
devtools say there is a fetch issue, status 500. 

Javascript is enabled by default and for the site specifically.

**Comment by sanyarnd** [comment]
So login works, you can authenticate, but something goes wrong when you're trying to fetch notifications, right?

**Comment by BrosefAmelion** [comment]
That's correct.
Login works no problem but a popup at the bottom says there is a connection error.

**Comment by sanyarnd** [comment]
I'll update the app sometime this week, and I'll make error messages more verbose.

I suspect that the issue comes from serialization, something have changed.

Until then you have to wait or try to run app locally with debug level:
https://github.com/sanyarnd/vocadb-notification-reader/blob/c056bea087afb9a8463ad2fac82514c43e7c1b13/src/main/rust/main.rs#L12

**Comment by BrosefAmelion** [comment]
Take your time, I'm in no rush.

**Comment by sanyarnd** [comment]
I updated the backend code, it should output verbose messages with a stacktrace.

Can you give it another try and say what the error is

**Comment by BrosefAmelion** [comment]
Still gives me the same connection error.

Checked devtools and it's the same fetch error, previewing the error says:

{code: 500, message: "Web client error: Unable to deserialize a payload",…}
code: 500
message: "Web client error: Unable to deserialize a payload"
stacktrace: ["input contains invalid characters at line 1 column 59"]

**Comment by sanyarnd** [comment]
Yeah, to fix the issue I need to understand what's wrong first :) 

Error sounds rather strange, I'll look through it in the logs, but I think I'd require your cooperation, do you have any messenger I can contact you with?

**Comment by BrosefAmelion** [comment]
What sort of messenger did you have in mind?

**Comment by sanyarnd** [comment]
Anything like telegram or Skype or discord

**Comment by BrosefAmelion** [comment]
Got discord.
BrosefAmelion#6319
