### ISSUE TITLE
Site giving an application error

### ISSUE THREAD

**Issue by BrosefAmelion** [sanyarnd/vocadb-notification-reader#13]
Says the applications owner needs to check the heroku logs.

**Comment by sanyarnd** [comment]
Hi, Heroku is dead (no more free tier), I'll migrate the app to my own server by the end of the next week, I hope.

**Comment by sanyarnd** [comment]
Right now you can use a local build, there's an instruction in README how to run a docker image yourself.

**Comment by sanyarnd** [comment]
Hi, everything should be working by now, you can access the app via https://vocadb-notification-reader.handystuff.net/login

It took some time to buy a domain, configure reverse proxy, https and change deployment process, but finally it's over :D

Fonts appear to be broken (icons), but I'll try to update the app asap.
