### ISSUE TITLE
Another connection error

### ISSUE THREAD

**Issue by BrosefAmelion** [sanyarnd/vocadb-notification-reader#15]
Tried the old fixes such as changing date format on Vocadb, reloading page, relogging etc.

**Comment by sanyarnd** [comment]
Glad to hear it was resolved.

Do you have steps to fix the issue?

**Comment by BrosefAmelion** [comment]
Not sure, it suddenly started working again but only for a minute before giving me another connection error so it may just be an issue on my end.
    On Friday, October 6, 2023 at 07:34:29 a.m. MDT, Alexander Biryukov ***@***.***> wrote:  
 
 


Glad to hear it was resolved.

Do you have steps to fix the issue?

**Comment by BrosefAmelion** [comment]
Odd thing is that there are 3 pages of notifications and only page 1 gives the connection error, I can view the other 2 no problem.
    On Friday, October 6, 2023 at 04:55:24 p.m. MDT, katty hawk ***@***.***> wrote:  
 
  Not sure, it suddenly started working again but only for a minute before giving me another connection error so it may just be an issue on my end.
    On Friday, October 6, 2023 at 07:34:29 a.m. MDT, Alexander Biryukov ***@***.***> wrote:  
 
 


Glad to hear it was resolved.

Do you have steps to fix the issue?

**Comment by kateabr** [comment]
Hi @BrosefAmelion , could you export the batch that gives the error? It can be done via the [swagger](https://vocadb.net/swagger/index.html): go to `/api/users/{id}/messages`, enter your id (`10972`) and set `inbox` to `Notifications`.

**Comment by BrosefAmelion** [comment]
The JSON file?
    On Sunday, October 8, 2023 at 06:21:04 a.m. MDT, Ekaterina Biryukova ***@***.***> wrote:  
 
 


Hi @BrosefAmelion , could you export the batch that gives the error? It can be done via the swagger: go to /api/users/{id}/messages, enter your id (10972) and set inbox to Notifications.

**Comment by kateabr** [comment]
Yep

**Comment by BrosefAmelion** [comment]
I think I found the issue, checked my messages on Vocadb finding one of them led to a 404 and once that was deleted I had my connection restored on your notification reader.
Link in questionhttps://vocadb.net/Error?code=404&redirect=True
    On Sunday, October 8, 2023 at 05:45:42 p.m. MDT, Ekaterina Biryukova ***@***.***> wrote:  
 
 


Yep
