### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by BrosefAmelion** [sanyarnd/vocadb-notification-reader#16]
Gives the error that the user/pass is invalid.
Made a new account and received the same error.

**Comment by sanyarnd** [comment]
Sorry for the delay, was your issue resolved?

**Comment by BrosefAmelion** [comment]
Might've been a hiccup in the system. Seems to recognize my login info now.
    On Monday, April 22, 2024 at 04:13:49 a.m. MDT, Alexander Biryukov ***@***.***> wrote:  
 
 


Sorry for the delay, was your issue resolved?

**Comment by sanyarnd** [comment]
Yeah, VocaDB is experimenting with login scenarios (adding extra cookies and stuff), since there is no contract, they're free to break things from time to time =|
