### ISSUE TITLE
Support for TouhouDB/UtaiteDB?

### ISSUE THREAD

**Issue by riipah** [sanyarnd/vocadb-notification-reader#4]
Should be just a matter of changing the endpoint. API is the same.

https://touhoudb.com/
https://utaitedb.net/

**Comment by sanyarnd** [comment]
I will. Do you have any specific name in mind for all of 3 projects (`VocaTouhouUtaiteReader` :D)?

**Comment by riipah** [comment]
Not really. Naming things is hard.

**Comment by sanyarnd** [comment]
@riipah I've added a basic field for service selection, nothing fancy (for now, there will be a small redesign later), but it's working.

https://unofficial-vocadb-ntf-reader.herokuapp.com/
